### ISSUE TITLE
Crash on Mac

### ISSUE THREAD

**Issue by BSVogler** [yannick95/NeuralNetworkTester#2]
> 2017-11-25 16:46:35.440 Python[12807:678928] -[NSApplication _setup:]: unrecognized selector sent to instance 0x7fd5ee997b00
2017-11-25 16:46:35.441 Python[12807:678928] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSApplication _setup:]: unrecognized selector sent to instance 0x7fd5ee997b00'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff38e952fb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff5f806c76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff38f2dda4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff38e0b670 ___forwarding___ + 1456
	4   CoreFoundation                      0x00007fff38e0b038 _CF_forwarding_prep_0 + 120
	5   Tk                                  0x00007fff452bb328 TkpInit + 467
	6   Tk                                  0x00007fff4523a262 Tk_Init + 1710
	7   _tkinter.cpython-36m-darwin.so      0x0000000102f07de9 Tcl_AppInit + 84
	8   _tkinter.cpython-36m-darwin.so      0x0000000102f0344a _tkinter_create + 1047
	9   Python                              0x000000010247a5bd _PyCFunction_FastCallDict + 166
	10  Python                              0x00000001024e1de0 call_function + 511
	11  Python                              0x00000001024da763 _PyEval_EvalFrameDefault + 4950
	12  Python                              0x00000001024e2586 _PyEval_EvalCodeWithName + 1786
	13  Python                              0x00000001024e2e9c _PyFunction_FastCallDict + 449
	14  Python                              0x00000001024410d3 _PyObject_FastCallDict + 214
	15  Python                              0x00000001024411f7 _PyObject_Call_Prepend + 156
	16  Python                              0x0000000102440f40 PyObject_Call + 102
	17  Python                              0x000000010248e153 slot_tp_init + 61
	18  Python                              0x000000010248aef9 type_call + 184
	19  Python                              0x0000000102441097 _PyObject_FastCallDict + 154
	20  Python                              0x00000001024e1da9 call_function + 456
	21  Python                              0x00000001024da763 _PyEval_EvalFrameDefault + 4950
	22  Python                              0x00000001024e2586 _PyEval_EvalCodeWithName + 1786
	23  Python                              0x00000001024d9393 PyEval_EvalCode + 42
	24  Python                              0x0000000102502049 run_mod + 54
	25  Python                              0x0000000102502353 PyRun_FileExFlags + 160
	26  Python                              0x000000010250182f PyRun_SimpleFileExFlags + 285
	27  Python                              0x0000000102515dd1 Py_Main + 3505
	28  Python                              0x0000000102433e1b Python + 7707
	29  libdyld.dylib                       0x00007fff603f5145 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
fish: ′python3 ./main.py' terminated by signal SIGABRT (Abort)

I am running macOS 10.13.1.
I thought maybe I am missing some module, however I get an error message for the following modules:

- threading
- subprocess
- tkinter

>   Could not find a version that satisfies the requirement subprocess (from versions: )
> No matching distribution found for subprocess

**Comment by yannick95** [comment]
I believe these modules are already pre-installed. Try to run the main.py file. If there's some required module missing, the output will tell you which one you have to install.

**Comment by ybrunken** [comment]
These modules should already be pre-installed, so that's probably not the reason. Unfortunately, I have no access to MacOS, so it's rather difficult for me to debug. But I'll try to find a solution

**Comment by ybrunken** [comment]
@BSVogler Could you please try it again if it's still crashing?

**Comment by BSVogler** [comment]
fixed
